pool:
  vmImage: 'ubuntu-latest'

jobs:

- job: sse2
  steps:
  - script: sudo apt-get update && sudo apt-get install -y ninja-build meson gcovr
    displayName: Dependencies
  - script: mkdir build && meson -Db_coverage=true -Db_sanitize=address,undefined CFLAGS='-msse2' CXXFLAGS='-msse2' build
    displayName: Configure
  - script: ninja -C build -v
    displayName: Build
  - script: ./build/test/run-tests
    displayName: Tests
  - script: ninja -C build -v coverage-xml
    displayName: Collect Coverage
  - script: if [ -e "build/meson-logs/coverage.xml" ]; then bash <(curl -s https://codecov.io/bash) -y .codecov.yml -f "build/meson-logs/coverage.xml"; fi
    displayName: Upload Coverage

- job: sse4_1
  steps:
  - script: sudo apt-get update && sudo apt-get install -y ninja-build meson gcovr
    displayName: Dependencies
  - script: mkdir build && meson -Db_coverage=true -Db_sanitize=address,undefined CFLAGS='-msse4.1' CXXFLAGS='-msse4.1' build
    displayName: Configure
  - script: ninja -C build -v
    displayName: Build
  - script: ./build/test/run-tests
    displayName: Tests
  - script: ninja -c build -v coverage-xml
    displayname: collect coverage
  - script: if [ -e "build/meson-logs/coverage.xml" ]; then bash <(curl -s https://codecov.io/bash) -y .codecov.yml -f "build/meson-logs/coverage.xml"; fi
    displayname: upload coverage

- job: mipsel
  vmImage: 'ubuntu-bionic'
  steps:
  - script: sudo apt-get update && sudo apt-get -y install gcc-8-mipsel-linux-gnu g++-8-mipsel-linux-gnu qemu-user-static binfmt-support python3-pip python3-setuptools ninja-build
    displayName: APT Dependencies
  - script: pip3 install meson gcovr
    displayName: Install meson
  - script: QEMU_LD_PREFIX=/usr/mipsel-linux-gnu/ CC=/usr/bin/mipsel-linux-gnu-gcc-8 CXX=/usr/bin/mipsel-linux-gnu-g++-8 meson -Db_coverage=true -Db_sanitize=address,undefined build
    displayName: Configure
  - script: QEMU_LD_PREFIX=/usr/mipsel-linux-gnu/ ninja -C build -v
    displayName: Build
  - script: QEMU_LD_PREFIX=/usr/mipsel-linux-gnu/ /usr/bin/qemu-mipsel-static ./build/test/run-tests
    displayName: Tests
  - script: if [ -e "build/meson-logs/coverage.xml" ]; then bash <(curl -s https://codecov.io/bash) -y .codecov.yml -f "build/meson-logs/coverage.xml"; fi
    displayName: Upload Coverage

