name: CI

on: [push, pull_request]

jobs:
  x86:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        isax: ["", "-msse3", "-mssse3", "-msse4.1", "-msse4.2", "-mavx", "-mfma", "-mavx2", "-march=native"]
    steps:
    - uses: actions/checkout@v2
    - name: Install APT Dependencies
      run: sudo add-apt-repository 'ppa:ubuntu-toolchain-r/test' && sudo apt-get update && sudo apt-get install -y ninja-build meson
    - name: Configure
      run: mkdir build && CFLAGS="${{ matrix-isax }} -Wall -Wextra -Werror" CXXFLAGS="${{ matrix.isax }} -Wall -Wextra -Werror" meson -Db_coverage=true -Db_sanitize=address,undefined build
    - name: Build
      run: ninja -C build -v && ./build/test/run-tests && ninja -C build -v coverage-xml
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  # emscripten:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install APT dependencies
  #     run: sudo apt-get install -y ninja-build nodejs
  #   - name: Dowvload Emscripten
  #     run: |
  #       git clone https://github.com/emscripten-core/emsdk.git && \
  #       emsdk/emsdk install latest && \
  #       emsdk/emsdk activate latest
  #   - name: Configure
  #     run: emsdk/upstream/emscripten/emconfigure cmake test -G "Ninja" -DCMAKE_BUILD_TYPE="Coverage" -DALWAYS_BUILD_NATIVE_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
  #   - name: Build
  #     run: emsdk/upstream/emscripten/emmake ninja
  #   - name: Test
  #     run: node ./run-tests=
